### ISSUE TITLE
racketcon 2022 link broken 404

### ISSUE THREAD

**Issue by jestarray** [racket/racket-lang-org#240]
https://con.racket-lang.org/2022 Visiting this url gives me a 404 uncaught exception

**Comment by spdegabrielle** [comment]
Folder looks ok
https://github.com/racket/racket-lang-org/blob/master/rcon/2022/index.rkt

I’m not clear how https://con.racket-lang.org/2022 is configured and built?

**Comment by sorawee** [comment]
That appears to be intentional. 

https://github.com/racket/racket-lang-org/blob/65c54d3770f332ee3e658bc515b219643d37ffb1/annual-utils.rkt#L39

For the current year, `index.html` won't be copied over. Instead, you can access it via the "main" site: https://con.racket-lang.org/

**Comment by spdegabrielle** [comment]
Lol
2022 at https://con.racket-lang.org/

**Comment by sorawee** [comment]
I do think that it's supposed to work though.

The problem appears to be due to https://github.com/racket/racket-lang-org/blob/master/sync.rkt#L132, which should update AWS configuration to redirect correctly. @jessealama updated the script for 2022, but I believe the script wasn't actually run. As a result, the config on AWS is still from 2021. And we can see this:

- https://con.racket-lang.org/2021/index.html is redirected to https://con.racket-lang.org/.
- https://con.racket-lang.org/2021/ works.
