### ISSUE TITLE
kiwiirc link on home page not working

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket-lang-org#331]
Seems to be a long term problem with kiwiirc.com

https://github.com/kiwiirc/kiwiirc/issues/1884

Is https://web.libera.chat/#racket an acceptable alternative?

**Comment by samth** [comment]
We should simply remove the link.

**Comment by LiberalArtist** [comment]
It looks like the IRC channel has the `r` mode set. Per [Libera.chat&rsquo;s docs](https://libera.chat/guides/webchat#linking-or-embedding):

> Keep in mind that webchat visitors frequently don’t have accounts. Often it’s their first time on IRC. If your channel has set the `+r` mode, then they will not be able to join. If the `+R` mode or `+q $~a` is used, then they will not be able to speak. You may need to reconsider the use of these modes. While it is a good idea to [advise users to register](https://libera.chat/guides/registration), if this is required it will discourage some users. If you need to require registration to participate in the channel, then channel mode `+R` is the least-discouraging way to do so.

If you try to use any of the IRC clients as a guest, you get the message `Cannot join channel (+r) - you need to be logged into your NickServ account`.

Given the extremely low level of activity on IRC, I think it would be more useful for `IRC` to link to some prose explaining this, and probably encouraging instead trying Discourse or other places where you are more likely to find people. It might also be worth considering `+R` instead of `+r`, but I don't know enough about the implications.

**Comment by spdegabrielle** [comment]
> We should simply remove the link.

https://github.com/racket/racket-lang-org/pull/332
