### ISSUE TITLE
'click for more' doesn't work on home page

### ISSUE THREAD

**Issue by joskoot** [racket/racket-lang-org#50]
Opening http://racket-lang.org/ under Windows 7 with internet explorer
shows a nice page, but boxes are not expanded when clicking them.

Using Google Chrome does work,
although its font is a little bit distorted (but well readable)

Thanks, Jos

**Comment by mbutterick** [comment]
I agree that the problem exists. However:

1) This problem arises because of [a bug in IE11](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview) that MS has said will not be fixed, because IE11 is now only getting security updates.

2) No one else has mentioned this problem, which suggests that among potential or current Racket users, IE11 is not a big factor.

3) Fixing this bug would mean that I have to re-engineer the whole layout to work around this bug, which will cause knock-on complications in every other browser. 

I’m afraid I can’t justify the labor. Sorry Jos.

**Comment by joskoot** [comment]
Thanks for looking into it.
Sorry for the trouble looking into a bug that is not Racket's.
As already planned, I'll soon replace my computer by a new one.
Then the problem will be solved for me.
Thanks again, Jos
